[build]
  command = "pnpm build"
  functions = "dist/netlify/functions"


[[redirects]]
  from = "/v2/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsdom"]
  included_files = [
    "node_modules/jsdom/lib/jsdom/browser/**",
    "node_modules/.pnpm/jsdom@*/node_modules/jsdom/lib/jsdom/browser/**"
  ]

[functions."*"]
  ignored_files = ["**/*.d.ts", "**/*.d.ts.map"]